k4m4/movies-for-hackers

README.md
Removed **Pirates of Silicon Valley**  that appeared twice in **Documentaries** list
=> Remove duplicated

README.md
Correct misspelling max rate on Pirates of Silicon Valley
=> Wrong max rate Pirates of Silicon Valley

README.md
=> Added original war games

README.md
WarGames deserves to be on this list for sure! This pull req fixes a formatting error.
=> Fixed stray newline: formatting error in table under wargames.

README.md
Updated readme.md to include the movie: Terms and Conditions may apply.
=> Updated Readme.md with new movie

README.md
After being betrayed and left for dead in Italy, Charlie Croker and his team plan an elaborate gold heist against their former ally.
=> Updated README.md to add The Italian Job.

README.md
=> Added World on a Wire to Science Fiction / Fantasy

README.md
Added The Imitation Game http://www.imdb.com/title/tt2084970/
=> added The Imitation Game

README.md
Great documentary that covers the 37 year history of the Dial-Up Bulletin Board System. It has more than 200 interviews with pioneers and enthusiasts. Also covers ANSI art, FIDONET, hacking and phreaking scenes of the 80s and 90s.
IMDB: http://www.imdb.com/title/tt0460402/
Synopsis: http://www.imdb.com/title/tt0460402/synopsis
=> Adding "BBS: The Documentary"

README.md
The original, and arguably the better of the two films. Fixes issue #30
=> Add Tron (1982)

README.md
https://www.youtube.com/watch?v=WEKl5I_Q044
=> add (Good Copy Bad Copy)

README.md
A paranoid mathematician searches for a key number that will unlock the universal patterns found in nature.
=> Add Pi (1998)

README.md
srsly, have you seen this movie? 7.0 is too low.
=> Add Primer

README.md
This one adds a pair of good 2014 movies: Transcendence and Listening, both a definitely must-see.
=> Add Transcendence and Listening

README.md
It's definitely not complete, but I felt like The IT Crowd and especially Mr. Robot definitely needed to be in this list.
=> Added the TV shows section

README.md
Add the film Echelon Conspiracy (2009) to the Action section. http://www.imdb.com/title/tt1124039/
=> Add Film > Action > Echelon Conspiracy (2009)

README.md
Set at the intersection of the near future and the reimagined past, explore a world in which every human appetite can be indulged.
=> Add Westworld (2016)

README.md
And that's about artificial intelligence and hackers' civil responsibility, featuring Joseph Weizenbaum.
=> Add Plug and Pray to documentaries

README.md
This one adds the very recent Ghost in the Shell movie based on the original manga of the same name.
=> Add Ghost in the Shell (2017)

README.md
Add  [Source Code](http://www.imdb.com/title/tt0945513/) movie
=> add source code movie

README.md
Proposing to add this movie to the list, has interesting view on a connected home being taken over by hacker.
=> Add Movie I.T.(2016)

README.md
- **Title**: Softwaring Hard
- **Link**: http://www.imdb.com/title/tt3063636/
- **Genre**: Documentary
- **Rating**: 8.2/10
=> Add Softwaring hard documentary

README.md
- **Title**: Scorpion
- **Link**: http://www.imdb.com/title/tt3514324/
- **Genre**: Action/Drama
- **Rating**: 7.2/10
<br/ >
- **Description**: An eccentric genius forms an international network of super-geniuses to act as the last line of defense against the complicated threats of the modern world.
=> Add Scorpion (2014)

README.md
- **Title**: CSI: Cyber
- **Link**: http://www.imdb.com/title/tt3560060/
- **Genre**: Crime/Drama/Mystery
- **Rating**: 5.4/10
<br/ >
- **Description**: Special agent Avery Ryan works to solve crimes as a CyberPsychologist for the FBI.
=> Add CSI: Cyber (2015)

README.md
----
- **Title**: Morgan
- **Link**: http://www.imdb.com/title/tt4520364/
- **Genre**: Science Fiction/Thriller
- **Rating**: 5.8/10
=> Add Morgan

movies-for-hackers.sh
=> Remove unused colors in movies-for-hackers.sh

readme.md
- **Title**: Silk Road: Drugs, Death and the Dark Web
- **Link**: http://www.imdb.com/title/tt7301126/
- **Genre**: Documentary
- **Rating**: 7.4/10
<br/ >
- **Description**:  An in depth documentary of the infamous Silk Road marketplace.
=> Add doc "Silk Road: Drugs, Death and the Dark Web"

readme.md
- **Title**: The Code
- **Link**: http://www.imdb.com/title/tt3914672/
- **Genre**: Drama
- **Rating**: 7.6/10
<br/ >
- **Description**: Two Canberra based brothers become entangled in a cover up that involves a remote outback community and key members of the Australian Government.
=> Adding TV series The code.

readme.md
- **Title**: The Signal
- **Link**: http://www.imdb.com/title/tt2910814/
- **Genre**: Thriller
- **Rating**: 6.1
<br/ >
- **Description**: 
"On a road trip, Nic and two friends are drawn to an isolated area by a computer genius. When everything suddenly goes dark, Nic regains consciousness - only to find himself in a waking nightmare." (Source: http://www.imdb.com/title/tt2910814/)
=> add the signal

.github/PULL_REQUEST_TEMPLATE.md
<br/ >
- **Description**: Fix broken link
=> Fix broken link

readme.md
-----
Apologies for the delay. I've fixed the problem (so I hope!).
Fixes #133, Revised version of #136.
=> Fix: Alphabetise the movie/TV titles.

readme.md
=> Add "Blade Runner 2049"

readme.md
- **Title**: 
- **Link**: 
- **Genre**: 
- **Rating**: 
<br/ >
- **Description**:
=> Add 2001: A Space Odyssey (1968)

readme.md
- [ x] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [ x] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.
- **Title**: The Island
- **Link**: https://www.imdb.com/title/tt0399201
- **Genre**: Action/Adventure
- **Rating**: 6.9
<br/ >
- **Description**: A man living in a futuristic sterile colony begins to question his circumscribed existence when his friend is chosen to go to the Island, the last uncontaminated place on earth.
=> adds the island movie

readme.md
- **Title**: 
- **Link**: 
- **Genre**: 
- **Rating**: 
<br/ >
- **Description**:
=> Fixed "Black Mirror" genre spacing

readme.md
- **Title**: StartUp
- **Link**: https://www.imdb.com/title/tt5028002/
- **Genre**: Crime/Thriller
- **Rating**: 8.1/10
<br/ >
- **Description**: A desperate banker, a Haitian-American gang lord, and a Cuban-American hacker are forced to work together to unwittingly create their version of the American dream - organized crime 2.0.
=> Add TV Show StartUp

readme.md
=> Add awesome-computer-history to "Other Cool Lists"

readme.md
- **The Matrix Reloaded**: 
- **https://www.imdb.com/title/tt0234215/**: 
- **Science Fiction/Action**: 
- **7.2/10**: 
<br/ >
- **Following the events of Matrix (1999), Neo and the rebel leaders estimate they have 72 hours until 250,000 probes discover Zion and destroy it and its inhabitants. Neo must decide how he can save Trinity from a dark fate in his dreams.**:
=> added a movie

readme.md
=> Updated HTTP links to secure HTTPS links

readme.md
=> Use jsDelivr instead of RawGit

readme.md
- **Title**: Valley of the Boom
- **Link**: https://www.imdb.com/title/tt7768092/
- **Genre**: Documentary/Drama
- **Rating**: 6.5
<br/ >
- **Description**: Docudrama crosscut with real interviews about the 1990s tech boom in the Silicon Valley.
=> Add Valley of the Boom

readme.md
- [+] I have carefully **read and comply** with the [Contributing Guidelines](https://github.com/k4m4/movies-for-hackers/blob/master/contributing.md) of this repo.
- [+] I have **searched** the [PRs](https://github.com/k4m4/movies-for-hackers/pulls) of this repo and believe that this is not a duplicate.
- **Title**: The Great Hack
- **Link**: https://www.imdb.com/title/tt9358204/
- **Genre**: Documentary
- **Rating**: 7.0/10
<br/ >
- **Description**: Explains how the extent of data scraping that is going on in today's world that is then being used for nefarious purposes.
=> Add The Great Hack (2019) Documentary

readme.md
- Replace all the scattered genres and sub genres with `<main genre>/<sub-genre>`
- Retained alphabetical order for sub-genres
- When a movie has mixed main-genres tags, alphabetical order is retained
Refs: #236
=> Consolidate the genre column

readme.md
- **Title**: Devs 
- **Link**: [https://www.imdb.com/title/tt8134186](https://www.imdb.com/title/tt8134186) 
- **Genre**: Drama/Mystery/Sci-Fi 
- **Rating**: 7.9 
<br/ >
- **Description**: A computer engineer investigates the secretive development division in her company, which she believes is behind the disappearance of her boyfriend. 
- Closes #244.
=> Add 'Devs'

readme.md
- **Title**: Hidden Figures
- **Link**: https://www.imdb.com/title/tt4846340
- **Genre**: Biography/Drama/History 
- **Rating**: 7.8
<br/ >
- **Description**: The story of a team of female African-American mathematicians who served a vital role in NASA during the early years of the U.S. space program.
=> Add Hidden Figures

readme.md
- **Title**: Wizards of the Electronic Age
- **Link**: https://www.imdb.com/title/tt1191116/
- **Genre**: Documentary
- **Rating**: 7.7/10
- **Description**: Hackers is a classic documentary about the midnight programmers that created the personal computer revolution.
=> Add Hackers: Wizards of the Electronic Age
